language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" -y
  - sudo add-apt-repository ppa:allegro/5.0 -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install clang-3.6 --force-yes; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - sudo apt-get install libunwind7-dev libicu-dev liballegro5-dev libgles2-mesa-dev
  - ${CXX} --version
  - ${CC} --version
  - mkdir ~/dependency-prefix
  - export PKG_CONFIG_PATH=~/dependency-prefix/lib/pkgconfig

env:
  - BUILD_TYPE="Release" MONOLITHIC_BUILD=off LTO=on SUGGESTIONS=off
  - BUILD_TYPE="Release" MONOLITHIC_BUILD=off LTO=off SUGGESTIONS=off
  - BUILD_TYPE="Release" MONOLITHIC_BUILD=off LTO=on SUGGESTIONS=on
  - BUILD_TYPE="Release" MONOLITHIC_BUILD=off LTO=off SUGGESTIONS=on

install:
  - pushd ./dependencies/tinyxml2 && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make && make install && popd;
  - pushd ./dependencies/glm && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make && make install && popd;
  - pushd ./dependencies/physfs && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make && make install && popd;

before_script:
  - cmake . -DGLM_INCLUDE_DIR=~/dependency-prefix/include -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DMONOLITHIC_BUILD=${MONOLITHIC_BUILD} -DLTO=${LTO} -DCLANG_TIDY="clang-tidy-3.6" -DEXTRA_SUGGESTIONS=${SUGGESTIONS}

script: make VERBOSE=1 && make test ARGS="-V"

after_script: if [ "$CXX" = "clang++" ];then pushd build && make tidy && popd; fi

os:
  - linux

