language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" -y
  - sudo add-apt-repository ppa:allegro/5.0 -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-5; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install clang-3.6 --force-yes; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - sudo apt-get install libunwind7-dev libicu-dev liballegro5-dev libgles2-mesa-dev
  - ${CXX} --version
  - ${CC} --version
  - mkdir ~/dependency-prefix
  - mkdir ~/cmake
  - pushd ~/cmake && wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz && tar -xzf cmake-3.3.1-Linux-x86_64.tar.gz && popd
  - export PATH=~/cmake/cmake-3.3.1-Linux-x86_64/bin:${PATH}
  - export PKG_CONFIG_PATH=~/dependency-prefix/lib/pkgconfig

env:
  - BUILD_TYPE="Release" LTO=on SUGGESTIONS=off
  - BUILD_TYPE="Release" LTO=on SUGGESTIONS=on

install:
  - pushd ./dependencies/tinyxml2 && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/glm && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/physfs && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;

before_script:
  - cmake . -DGLM_INCLUDE_DIR=~/dependency-prefix/include -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLTO=${LTO} -DCLANG_TIDY="clang-tidy-3.6" -DEXTRA_SUGGESTIONS=${SUGGESTIONS}

script: make -j2 && make test ARGS="-V"

after_script:
  - if [ "$CXX" = "clang++-3.6" ];then make tidy; fi

os:
  - linux

