language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
#  - clang

matrix:
  exclude:
    - compiler: gcc
      env: TIDY="true"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main" -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-5 -y; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install clang-3.8 --force-yes -y; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - if [ "${TIDY}" = "true" ]; then sudo apt-get install clang-tidy-3.8 clang-format-3.8 --force-yes -y; fi
  - sudo apt-get install libunwind8-dev libsdl2-dev libboost-locale-dev -y
  - ${CXX} --version
  - ${CC} --version
  - mkdir ~/dependency-prefix
  - export PKG_CONFIG_PATH=~/dependency-prefix/lib/pkgconfig

env:
  - BUILD_TYPE="Release"
  - TIDY="true"

install:
  - pushd ./dependencies/tinyxml2 && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/glm && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/physfs && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;

before_script:
  - cmake . -DGLM_INCLUDE_DIR=~/dependency-prefix/include -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCLANG_TIDY=clang-tidy-3.8 -DCLANG_FORMAT=clang-format-3.8
# Do the format before the script so the output is cleaner - just showing the diff (if any) and the tidy results
  - if [ "${TIDY}" = "true" ]; then make format -j2; fi

script:
  - if [ "${TIDY}" != "true" ]; then make -j2; fi
  - if [ "${TIDY}" = "true" ]; then git --no-pager diff --ignore-submodules && make tidy; fi

os:
  - linux

