version: '{branch}-0.0.{build}'
branches:
  except:
  - master
skip_tags: true
os: Visual Studio 2015
configuration:
  - Release
#  - Debug
platform:
  - x64
  - Win32
clone_depth: 10
before_build:
- git submodule init
- git submodule update
- nuget restore OpenApoc.sln
- curl http://s2.jonnyh.net/pub/cd_minimal.iso.xz -o data\cd.iso.xz
- 7z e data\cd.iso.xz -odata\
build:
  project: OpenApoc.sln
  verbosity: normal
after_build:
- mkdir OpenApoc-DEV
- echo %APPVEYOR_REPO_COMMIT% > OpenApoc-DEV\git-commit
- echo %APPVEYOR_BUILD_VERSION% > OpenApoc-DEV\build-id
- copy bin\%PLATFORM%\%CONFIGURATION%\*.dll OpenApoc-DEV\
- copy bin\%PLATFORM%\%CONFIGURATION%\*.exe OpenApoc-DEV\
- copy bin\%PLATFORM%\%CONFIGURATION%\*.pdb OpenApoc-DEV\
- del data\cd.iso
- del data\cd.iso.xz
- xcopy /E data OpenApoc-DEV\data\
- 7z a OpenApoc-msvc-dev.zip OpenApoc-DEV
artifacts:
- path: OpenApoc-msvc-dev.zip
  name: built-zip
