version: 0.0.{build}
branches:
  only:
  - master
  - /release.*/
skip_tags: true
os: Visual Studio 2015
configuration:
  - Release
#  - Debug
platform:
  - x64
  - Win32
clone_depth: 10
before_build:
- git submodule init
- git submodule update
- nuget restore OpenApoc.sln
- curl http://s2.jonnyh.net/pub/cd_minimal.iso.xz -o data\cd.iso.xz
- 7z e data\cd.iso.xz -odata\
build:
  project: OpenApoc.sln
  verbosity: normal
after_build:
- mkdir OpenApoc-%APPVEYOR_BUILD_VERSION%
- echo %APPVEYOR_REPO_COMMIT% > OpenApoc-%APPVEYOR_BUILD_VERSION%\git-commit
- echo %APPVEYOR_BUILD_VERSION% > OpenApoc-%APPVEYOR_BUILD_VERSION%\build-id
- copy bin\%PLATFORM%\%CONFIGURATION%\*.dll OpenApoc-%APPVEYOR_BUILD_VERSION%\
- copy bin\%PLATFORM%\%CONFIGURATION%\*.exe OpenApoc-%APPVEYOR_BUILD_VERSION%\
- del data\cd.iso
- del data\cd.iso.xz
- xcopy /E data OpenApoc-%APPVEYOR_BUILD_VERSION%\data\
- 7z a OpenApoc-msvc.zip OpenApoc-%APPVEYOR_BUILD_VERSION%
- copy bin\%PLATFORM%\%CONFIGURATION%\*.pdb OpenApoc-%APPVEYOR_BUILD_VERSION%\
- copy portable.txt OpenApoc-%APPVEYOR_BUILD_VERSION%\
- 7z a OpenApoc-msvc-debug.zip OpenApoc-%APPVEYOR_BUILD_VERSION%\*.pdb
artifacts:
- path: OpenApoc-msvc.zip
  name: built-zip
- path: OpenApoc-msvc-debug.zip
  name: debug-zip
