version: '{branch}-0.0.{build}'
branches:
  except:
  - master
skip_tags: true
os: Visual Studio 2015
configuration:
  - Release
#  - Debug
platform:
  - x64
  - Win32
clone_depth: 10
before_build:
- git submodule init
- git submodule update
- nuget restore OpenApoc.sln
- curl http://s2.jonnyh.net/pub/cd_minimal.iso.xz -o data\cd.iso.xz
- 7z e data\cd.iso.xz -odata\
build:
  project: OpenApoc.sln
  verbosity: normal
after_build:
- mkdir OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%
- echo %APPVEYOR_REPO_COMMIT% > OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%\git-commit
- echo %APPVEYOR_BUILD_VERSION% > OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%\build-id
- copy bin\%PLATFORM%\%CONFIGURATION%\*.dll OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%\
- copy bin\%PLATFORM%\%CONFIGURATION%\*.exe OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%\
- del data\cd.iso
- del data\cd.iso.xz
- xcopy /E data OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%\data\
- 7z a OpenApoc-dev-msvc.zip OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%
- copy bin\%PLATFORM%\%CONFIGURATION%\*.pdb OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%\
- 7z a OpenApoc-dev-msvc-debug.zip OpenApoc-Dev-%APPVEYOR_BUILD_VERSION%\*.pdb
artifacts:
- path: OpenApoc-dev-msvc.zip
  name: built-zip
- path: OpenApoc-dev-msvc-debug.zip
  name: debug-zip
