version: '{branch}-0.0.{build}'
branches:
  except:
  - master
skip_tags: true
configuration: Release
platform: x64
clone_depth: 10
before_build:
- git submodule init
- git submodule update
build:
  project: OpenApoc.sln
  verbosity: normal
after_build:
- mkdir OpenApoc-%APPVEYOR_BUILD_VERSION%
- echo %APPVEYOR_REPO_COMMIT% > OpenApoc-%APPVEYOR_BUILD_VERSION%\git-commit
- echo %APPVEYOR_BUILD_VERSION% > OpenApoc-%APPVEYOR_BUILD_VERSION%\build-id
- copy x64\Release\*.dll OpenApoc-%APPVEYOR_BUILD_VERSION%\
- copy x64\Release\OpenApoc.exe OpenApoc-%APPVEYOR_BUILD_VERSION%\
- xcopy /E data OpenApoc-%APPVEYOR_BUILD_VERSION%\data\
- 7z a OpenApoc-msvc-dev.zip OpenApoc-%APPVEYOR_BUILD_VERSION%
artifacts:
- path: OpenApoc-msvc-dev.zip
  name: built-zip
