version: '{branch}-0.0.{build}'
branches:
  except:
  - master
  - /release.*/
skip_tags: true
os: Visual Studio 2015
configuration:
  - Release
#  - Debug
platform:
  - x64
#  - Win32
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
init:
  - if "%PLATFORM%"=="x64" (set VCPKG_DEFAULT_TRIPLET=x64-windows)
  - if "%PLATFORM%"=="x64" (set VCVARS_ARCH=amd64)
  - if "%PLATFORM%"=="Win32" (set VCPKG_DEFAULT_TRIPLET=x86-windows)
  - if "%PLATFORM%"=="Win32" (set VCVARS_ARCH=amd64_x86)
#clone_depth: 10
cache: c:\tools\vcpkg\installed
before_build:
  - vcpkg install sdl2 boost-locale boost-system boost-program-options boost-filesystem boost-uuid boost-crc
  - vcpkg upgrade --no-dry-run
  - git submodule update --init --recursive
  - curl http://s2.jonnyh.net/pub/cd_minimal.iso.xz -o temp\cd.iso.xz
  - 7z e temp\cd.iso.xz -odata\
  - choco install ninja
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %VCVARS_ARCH%
build_script:
  - cmake -DMSVC_PDB=ON . -GNinja -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
  - cmake --build .
after_build:
  - git describe --tags > build-id
  - set /p OPENAPOC_VERSION= < build-id
  - set OPENAPOC_FILENAME=OpenApoc-%PLATFORM%-%OPENAPOC_VERSION%.7z
  - set OPENAPOC_DEBUG_FILENAME=OpenApoc-debug-%PLATFORM%-%OPENAPOC_VERSION%.7z
  - mkdir OpenApoc-%OPENAPOC_VERSION%
  - echo %APPVEYOR_REPO_COMMIT% > OpenApoc-%OPENAPOC_VERSION%\git-commit
  - echo %OPENAPOC_VERSION% > OpenApoc-%OPENAPOC_VERSION%\build-id
  - copy bin\*.dll OpenApoc-%OPENAPOC_VERSION%\
  - copy bin\OpenApoc.exe OpenApoc-%OPENAPOC_VERSION%\
  - del data\cd.iso
  - xcopy /E data OpenApoc-%OPENAPOC_VERSION%\data\
  - copy portable.txt OpenApoc-%OPENAPOC_VERSION%\
  - copy README.md OpenApoc-%OPENAPOC_VERSION%\README.txt
  - copy README_HOTKEYS.txt OpenApoc-%OPENAPOC_VERSION%\
  - 7z a %OPENAPOC_FILENAME% OpenApoc-%OPENAPOC_VERSION% -mx=9 -myx=7
  - copy bin\OpenApoc.pdb OpenApoc-%OPENAPOC_VERSION%\
  - 7z a %OPENAPOC_DEBUG_FILENAME% OpenApoc-%OPENAPOC_VERSION%\*.pdb -mx=9 -myx=7
  - appveyor PushArtifact %OPENAPOC_FILENAME%
  - appveyor PushArtifact %OPENAPOC_DEBUG_FILENAME%
before_test:
  - 7z e temp\cd.iso.xz -odata\
test_script:
  - ctest -V -C %CONFIGURATION%
